### ISSUE TITLE
Regression Table & Factors

### ISSUE THREAD

**Issue by mjbsp** [dstanley4/apaTables#1]
I really like the package. I ran into a small problem when I tried to create a regression table for an equation where one variable was a factor (and so dummy coded). I received the following error.

> Error in cor.test.default(dv.in, cur.pred) : 'y' must be a numeric vector

The same model without the factor variable worked great.

I know that I can create my own dummy codes and avoid the issue, but it would also be handy to use factors in the models.

**Comment by dstanley4** [comment]
I just uploaded a new version of apaTables to the CRAN (version 1.5.0). I believe this should address this issue. If not, please let me know.

Also note, that there is now a short vignette for the package: 
https://cran.r-project.org/web/packages/apaTables/vignettes/apaTables.html

Cheers,
David
