### ISSUE TITLE
Error in 2:last_model_number_predictors : argument of length 0

### ISSUE THREAD

**Issue by peteralynn** [dstanley4/apaTables#22]
Hello,
I am getting the error "Error in 2:last_model_number_predictors : argument of length 0" in trying to create tables for a relatively simple model.

I see that this is essentially the same problem as was reported here, https://github.com/dstanley4/apaTables/issues/13 , but the proposed solutions therein do not help.  In addition, I cannot install the development version, as I get the following error:

Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/dstanley4/apaTables/tarball/master'

Any thoughts?  I have some existing tables that apaTables made with which I'd like to keep the present tables consistent; your assistance would be much appreciated.

Thanks,
Peter

**Comment by peteralynn** [comment]
...let's just say I figured this one out on my own.
(I was feeding it a summary object rather than the lm object itself.)

**Comment by homataheri** [comment]
Hi,

I experienced the same error while reporting a clustered logistic regression.

model1 <- miceadds::glm.cluster(data=df_clean3, formula=recall ~ log(Population)+NoComplaintsReported+NoCrashesFiresReported+NoInjuriesReported+NoFatalityIncidentsReported+NoOtherFailuresReported+YearOpen+label, cluster="label", family="binomial")

apa.reg.table(model1)

Error: Error in 2:last_model_number_predictors : argument of length 0

May I have your assistance on this issue?

**Comment by dstanley4** [comment]
At this time apaTables (apa.reg.table) only supports output from the lm command.

On Mar 28, 2022, at 11:54 AM, homataheri ***@***.***> wrote:

﻿

CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to ***@***.***


Hi,

I experienced the same error while reporting a clustered logistic regression.

model1 <- miceadds::glm.cluster(data=df_clean3, formula=recall ~ log(Population)+NoComplaintsReported+NoCrashesFiresReported+NoInjuriesReported+NoFatalityIncidentsReported+NoOtherFailuresReported+YearOpen+label, cluster="label", family="binomial")

apa.reg.table(model1)

Error: Error in 2:last_model_number_predictors : argument of length 0

May I have your assistance on this issue?
