### ISSUE TITLE
apa.2way.table

### ISSUE THREAD

**Issue by dfeistauer** [dstanley4/apaTables#28]
is there a bug in apaTables::apa.2way.table?

the code breaks at this point.
iv1 <- as.factor(data[, iv1.name])

iv1 is a Factor named Job in my data
iv1.name is a chr = "\"Job\""

Thanks.

**Comment by dstanley4** [comment]
The example code works fine, so I suspect it’s your call of the the command. Can you send a bit more of the script doing the calling?

On Jun 12, 2020, at 11:57 AM, dfeistauer <notifications@github.com<mailto:notifications@github.com>> wrote:


CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to IThelp@uoguelph.ca<mailto:IThelp@uoguelph.ca>




is there a bug in apaTables::apa.2way.table?

the code breaks at this point.
iv1 <- as.factor(data[, iv1.name])

iv1 is a Factor named Job in my data
iv1.name is a chr = ""Job""

Thanks.

**Comment by dfeistauer** [comment]
Sorry for the issue. I found the error. Thanks
