### ISSUE TITLE
Output of Results in LaTeX Format

### ISSUE THREAD

**Issue by amaddio** [dstanley4/apaTables#38]
I have noticed that LaTeX format is basically already supported when one looks at `apa.reg.table` function e.g. Line 147 

```R
block_out_latex <- rbind(model_label_line_latex, block_out_latex)
```

Is there any reason that LaTeX is supported but not offered by the public outer function? It would be super helpful to take advantage of this great work also for LaTeX users.

I am using `apaTables` package version: `2.0.8`

**Comment by dstanley4** [comment]
The feature is in development and not yet complete. Once complete it will be a public function.
On Jun 8, 2023 at 8:58 AM -0400, Antonio ***@***.***>, wrote:

CAUTION: This email originated from outside of the University of Guelph. Do not click links or open attachments unless you recognize the sender and know the content is safe. If in doubt, forward suspicious emails to ***@***.***


I have noticed that LaTeX format is basically already supported when one looks at apa.reg.table function e.g. Line 147

block_out_latex <- rbind(model_label_line_latex, block_out_latex)

Is there any reason that LaTeX is supported but not offered by the public outer function? It would be super helpful to take advantage of this great work also for LaTeX users.

I am using apaTables package version: 2.0.8

**Comment by amaddio** [comment]
Awesome thanks. Looking forward. Let me know if I can test or contribute.

**Comment by dstanley4** [comment]
If you download the development version from GitHub - you should be able to use the new apa.knit.table.for.pdf() command. There is also new app.save() command that you can use to save multiple tables in one file.

install.packages("remotes")

remotes::install_github("dstanley4/apaTables")

**Comment by amaddio** [comment]
Great, thanks for the update! I'll check it out and give feedback.
